// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gbmtest;

#nullable disable

namespace gbmtest.Migrations
{
    [DbContext(typeof(ProyectContext))]
    [Migration("20231219205552_AddIvaToFactura")]
    partial class AddIvaToFactura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("gbmtest.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cliente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d28b6ea-32e8-497b-9f52-07f211ac20ca"),
                            Codigo = "C1",
                            Direccion = "Managua",
                            Nombre = "Cliente 1"
                        },
                        new
                        {
                            Id = new Guid("3d28b6ea-32e8-497b-9f52-07f211ac20cb"),
                            Codigo = "B1",
                            Direccion = "Granaga",
                            Nombre = "Cliente 2"
                        });
                });

            modelBuilder.Entity("gbmtest.Models.DetalleFactura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleFactura", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d28b6ea-32e8-497b-9f52-07f211ac20cd"),
                            Cantidad = 1,
                            FacturaId = new Guid("3d28b6ea-32e8-497b-9f52-07f211ac20cc"),
                            PrecioUnitario = 100m,
                            ProductoId = new Guid("dc131c19-84af-4627-902a-08e3d5c98791")
                        },
                        new
                        {
                            Id = new Guid("3d28b6ea-32e8-497b-9f52-07f211ac20ce"),
                            Cantidad = 2,
                            FacturaId = new Guid("3d28b6ea-32e8-497b-9f52-07f211ac20cc"),
                            PrecioUnitario = 200m,
                            ProductoId = new Guid("dc131c19-84af-4627-902a-08e3d5c98792")
                        });
                });

            modelBuilder.Entity("gbmtest.Models.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Factura", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d28b6ea-32e8-497b-9f52-07f211ac20cc"),
                            ClienteId = new Guid("3d28b6ea-32e8-497b-9f52-07f211ac20ca"),
                            Fecha = new DateTime(2023, 12, 19, 14, 55, 52, 674, DateTimeKind.Local).AddTicks(2232),
                            Iva = 0m
                        },
                        new
                        {
                            Id = new Guid("3d28b6ea-32e8-497b-9f52-07f211ac20cb"),
                            ClienteId = new Guid("3d28b6ea-32e8-497b-9f52-07f211ac20cb"),
                            Fecha = new DateTime(2023, 12, 19, 14, 55, 52, 674, DateTimeKind.Local).AddTicks(2252),
                            Iva = 0m
                        });
                });

            modelBuilder.Entity("gbmtest.Models.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("PrecioCordobas")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecioDolares")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Producto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc131c19-84af-4627-902a-08e3d5c98791"),
                            Descripcion = "Producto 1",
                            PrecioCordobas = 100m,
                            PrecioDolares = 10m,
                            SKU = "P1"
                        },
                        new
                        {
                            Id = new Guid("dc131c19-84af-4627-902a-08e3d5c98792"),
                            Descripcion = "Producto 2",
                            PrecioCordobas = 200m,
                            PrecioDolares = 20m,
                            SKU = "P2"
                        });
                });

            modelBuilder.Entity("gbmtest.Models.TasaDeCambio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("TasaDeCambio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f789837c-ddd3-4451-be64-57996acf89ce"),
                            Fecha = new DateTime(2023, 12, 19, 14, 55, 52, 674, DateTimeKind.Local).AddTicks(2263),
                            Valor = 36m
                        });
                });

            modelBuilder.Entity("gbmtest.Models.DetalleFactura", b =>
                {
                    b.HasOne("gbmtest.Models.Factura", "Factura")
                        .WithMany("DetallesFactura")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("gbmtest.Models.Producto", "Producto")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("gbmtest.Models.Factura", b =>
                {
                    b.HasOne("gbmtest.Models.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("gbmtest.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("gbmtest.Models.Factura", b =>
                {
                    b.Navigation("DetallesFactura");
                });

            modelBuilder.Entity("gbmtest.Models.Producto", b =>
                {
                    b.Navigation("DetallesFacturas");
                });
#pragma warning restore 612, 618
        }
    }
}
